### ISSUE TITLE
get_result alternative needed

### ISSUE THREAD

**Issue by atutor** [atutor/AContent#26]
get_result() is only available when the mysqlind module is installed. This was a problem when trying to setup on http://atutordemos.x10host.com.

https://github.com/atutor/AContent/blob/9ff6ac538919e9a138953ec34ff1bb6abe05da62/include/classes/DAO/DAO.class.php#L84

I did find a piece of code (function get_result()) that returns an array, but the output needs to be a $stmt->execute() object.

Here's where the piece of code came from:
https://stackoverflow.com/questions/10752815/mysqli-get-result-alternative

What can be done to mimic $mysqli->get_result?

**Comment by cindyli** [comment]
I guess you meant the input of `get_result()` function needs to be an output of `$stmt->execute()` result. 

But [Line 81](https://github.com/atutor/AContent/blob/9ff6ac538919e9a138953ec34ff1bb6abe05da62/include/classes/DAO/DAO.class.php#L81) already uses `$stmt->execute()`. It seems moving the location of `if` should fix the issue. The logic looks:
```
// all steps for preparing statement are here
$stmt->execute()
if (extension_loaded("mysqlind"))  // Please double check if extension_loaded() can be used in this case
{
    $results = $stmt->get_result();
    // populate query result $rows[] with $results->fetch_array()
} else {
    $results = get_result( $stmt );
    // populate query result $rows[] with array_shift($results)
}
return $rows;
```
Let me know if I misunderstood the question.

**Comment by atutor** [comment]
The trouble is getting the function get_results($stmt) to return the same thing as $stmt->get_results.

The get_result() function is further down the file. It returns an array. Instead we need what $stmt->get_results returns. 

`    // Used if mysqlnd is not installed
    function get_result( $Statement ) {
        $RESULT = array();
        $Statement->store_result();
        for ( $i = 0; $i < $Statement->num_rows; $i++ ) {
            $Metadata = $Statement->result_metadata();
            $PARAMS = array();
            while ( $Field = $Metadata->fetch_field() ) {
                $PARAMS[] = &$RESULT[ $i ][ $Field->name ];
            }
            call_user_func_array( array( $Statement, 'bind_result' ), $PARAMS );
            $Statement->fetch();
        }
        return $RESULT;
    }`

**Comment by cindyli** [comment]
What `execute()` function eventually returns is fetched rows. When there are two different `get_results()` functions return different datasets, I think as long as there are two different parsers afterwards that handle these two datasets and return the same `$rows` result, things are still fine.

**Comment by atutor** [comment]
Could you write a bit of code that would align what the two functions' output.

**Comment by cindyli** [comment]
I sent the pull request https://github.com/atutor/AContent/pull/27 for this issue.

**Comment by atutor** [comment]
I'll kick myself for that one! I've been looking at that file for too long :-(

Glad it was an easy fix. Thanks again.
